server:
  port: 9092
  
spring:
  application: 
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:product_db
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  resources: 
      chain: 
        enabled: true
  main: 
    allow-bean-definition-overriding: true
        
    
logging:
  level: 
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
        